import Button from '../shared/Button'

const Toolbar = ({ blueprint, onNew }) => {
  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  /**
   * Download Blueprint as TXT File
   */
  const handleDownloadBlueprint = () => {
    const analysis = blueprint.generatedAnalysis

    const content = `
========================================
        LAUNCHPILOT AI BLUEPRINT
========================================

Startup Idea:
${blueprint.startupIdea}

Target Audience:
${blueprint.targetAudience}

Budget Range:
${blueprint.budgetRange}

Platform Type:
${blueprint.platformType}

========================================
PRODUCT OVERVIEW
========================================

Summary:
${analysis.productOverview.summary}

Value Proposition:
${analysis.productOverview.valueProposition}

Problem & Solution:
${analysis.productOverview.problemAndSolution}

========================================
CORE FEATURES
========================================

${analysis.coreFeatures
  .map(
    (feature) => `
- ${feature.name}
Priority: ${feature.priority}
Description: ${feature.description}
`
  )
  .join('\n')}

========================================
TECHNOLOGY STACK
========================================

Frontend:
${analysis.technologyStack.frontend.join(', ')}

Backend:
${analysis.technologyStack.backend.join(', ')}

Database:
${analysis.technologyStack.database.join(', ')}

Infrastructure:
${analysis.technologyStack.infrastructure.join(', ')}

========================================
MONETIZATION STRATEGY
========================================

${analysis.monetizationStrategy.businessModel}

========================================
DEVELOPMENT ROADMAP
========================================

Estimated Timeline:
${analysis.developmentRoadmap.estimatedTimeline}

========================================
SUCCESS METRICS
========================================

${analysis.successMetrics.kpis.join(', ')}

========================================
Generated by LaunchPilot AI
========================================
`

    const blob = new Blob([content], {
      type: 'text/plain;charset=utf-8',
    })

    const url = URL.createObjectURL(blob)

    const link = document.createElement('a')

    link.href = url
    link.download = `${blueprint.startupIdea
      .replace(/\s+/g, '-')
      .toLowerCase()}-blueprint.txt`

    document.body.appendChild(link)
    link.click()

    document.body.removeChild(link)

    URL.revokeObjectURL(url)
  }

  return (
    <div className="sticky top-0 z-40 glass-effect border-b border-white/10 px-8 py-4">
      <div className="flex items-center justify-between">
        {/* Metadata */}
        <div className="flex items-center gap-6">
          <div>
            <p className="text-sm text-gray-400">Created</p>
            <p className="text-sm font-medium text-gray-200">
              {formatDate(blueprint.createdAt)}
            </p>
          </div>

          <div>
            <p className="text-sm text-gray-400">Blueprint Type</p>
            <p className="text-sm font-medium text-cyan-400">
              AI Generated
            </p>
          </div>

          <div>
            <p className="text-sm text-gray-400">Status</p>
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-green-500"></span>
              <p className="text-sm font-medium text-gray-200">
                Ready
              </p>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-4">
          <Button
            onClick={handleDownloadBlueprint}
            variant="primary"
            size="small"
          >
            Download Blueprint
          </Button>

          <Button
            onClick={onNew}
            variant="secondary"
            size="small"
          >
            New Blueprint
          </Button>
        </div>
      </div>
    </div>
  )
}

export default Toolbar